kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: maven-pv-claim
    namespace: pipeline
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/maven
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - work01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pv-claim
  namespace: pipeline
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi